In [ ]:
Ml
workflow
     1. problem definition - define the objective
     2. Data collection - collection, identify the attributes ( features or input, target var, label, output)
     3. data preprocessing - Data cleaning( handle missing values , duplicates, data type formatting), feature scaling(standardization or normalization), encoding ( Gender - Male/Female)
     4. EDA ( Visualize feature distributes,analysis correleation between features, identify outliers)
     5. Feature Engineering  ( Patient ID, Hospital ID, patientname, BMI, age, Glue) - select important features)
     6. Data Spliting - Train(80%) Test (20%)  - validation (optional)
     7. Model Selection - ML algorithms - Supervised learning alg
     8. Train model (training set)
     9. Evalaute the model (accuracy, precision,recall, f1-score, confusion matrix, ROC-AUC curve)
     10.Hyperparameter tuning
     11. prediction (unknown data - test data)
     12. deployment ( REst API, web API, Web app)


ML - CPU , GPU , TPU   -CPU(why?) - it is not a complex data , simple dataset (<20,000 records)

ML
   - core Python
   - pandas, matplotlib, scipy, numpy, seaborn
   - scikit learn (python ML lib) - ML algorithms(supervised, unsupervised, reinforcement) - classes, functions, methods
   - pyspark (MLlib lib)

deployment
      web app - flask
      API - flask or FastAPI



Supervised LEarning alg
           - classification  (types - Binary (True/False)classification (only two classess in the output )
                                      Multi - class classification ( >=50k,<=50k ,50k)), Multi-label classification (multiple output)
                            - heart disease prediction based on the health metrics
           - regression    - output continuous value
                            - house price prediction, value  - gold price prediction
classification



In [ ]:
# problem statement
predict the customer will be going to purchase the product or not


In [2]:
# Data collection from different data sources

!pip install wget


  Preparing metadata (setup.py) ... done
  Created wheel for wget: filename=wget-3.2-py3-none-any.whl size=9655 sha256=91fd1b864ec25607acc6fe2cb50a50f831df702bf4491e42ea6e5ec3d6e87f5c
  Stored in directory: /root/.cache/pip/wheels/40/b3/0f/a40dbd1c6861731779f62cc4babcb234387e11d697df70ee97
Successfully built wget


In [3]:
import wget
wget.download('https://raw.githubusercontent.com/johnpaulantony/Machine-Learning/refs/heads/main/Logistic Regression/DigitalAd_dataset.csv')

'DigitalAd_dataset.csv'

In [6]:
# Data Exploration
# pandas - panel data system ( data analysis python lib)

#Pandas - two data sturutures - Series, DataFrame (1.0 - Panel)

import pandas as pd
dataset=pd.read_csv('DigitalAd_dataset.csv') # read_csv() - csv file format into dataframe (table format) object
type(dataset)
dataset

,Age,Salary,Status
0,18,82000,0
1,29,80000,0
2,47,25000,1
3,45,26000,1
4,46,28000,1
...,...,...,...
395,35,65000,0
396,26,80000,0
397,26,52000,0
398,20,86000,0


In [ ]:
dataset.head()

,Age,Salary,Status
0,18,82000,0
1,29,80000,0
2,47,25000,1
3,45,26000,1
4,46,28000,1


In [ ]:
dataset.tail()

,Age,Salary,Status
395,35,65000,0
396,26,80000,0
397,26,52000,0
398,20,86000,0
399,32,18000,0


In [ ]:
dataset.shape

(400, 3)

In [ ]:
# Data preprocessing

# Data Cleaning

# missing values - NaN, None, NaT etc

dataset.isna().sum()

,0
Age,0
Salary,0
Status,0


In [ ]:
dataset.dtypes

,0
Age,int64
Salary,int64
Status,int64


In [ ]:
pandas - int64, float64, object, bool, datetime64, timedelta64

In [10]:
# duplicated
dataset.duplicated().sum()

np.int64(33)

In [14]:
# Data Segregation - X or features or input  , Y (Target var, label, output)

X=dataset.loc[:, "Age":"Salary"].values
X

array([[    18,  82000],
       [    29,  80000],
       [    47,  25000],
       [    45,  26000],
       [    46,  28000],
       [    48,  29000],
       [    45,  22000],
       [    47,  49000],
       [    48,  41000],
       [    45,  22000],
       [    46,  23000],
       [    47,  20000],
       [    49,  28000],
       [    47,  30000],
       [    29,  43000],
       [    31,  18000],
       [    31,  74000],
       [    27, 137000],
       [    21,  16000],
       [    28,  44000],
       [    27,  90000],
       [    35,  27000],
       [    33,  28000],
       [    30,  49000],
       [    26,  72000],
       [    27,  31000],
       [    27,  17000],
       [    33,  51000],
       [    35, 108000],
       [    30,  15000],
       [    28,  84000],
       [    23,  20000],
       [    25,  79000],
       [    27,  54000],
       [    30, 135000],
       [    31,  89000],
       [    24,  32000],
       [    18,  44000],
       [    29,  83000],
       [    35,  23000],


In [ ]:
X=dataset.iloc[:,0:2].values
X

In [15]:
Y=dataset.loc[:,'Status'].values
Y

array([0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1,
       0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1,
       0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0,

In [11]:
# Data Splitting - train and test data

# sklearn module - all ML alg written in this lib


!pip install scikit-learn



In [32]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test=train_test_split(X,Y, test_size=0.2,random_state=0)

In [34]:
len(X_train)

320

In [35]:
len(Y_train)

320

In [36]:
len(X_test) == len(Y_test)

True

In [37]:
# feature scaling - model will give prioroty for all features during training

from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.transform(X_test)

In [38]:
X_train

array([[ 0.02212156,  1.24324249],
       [-0.9344866 ,  0.46784687],
       [-0.64750415, -0.09878838],
       [-0.16920007,  0.10997197],
       [ 0.11778238,  0.22926361],
       [ 1.74401625,  0.97483631],
       [-1.69977312,  0.31873233],
       [ 0.11778238, -0.00931966],
       [-0.26486088, -0.18825711],
       [ 0.11778238,  1.51164866],
       [ 0.11778238, -0.36719456],
       [-0.07353925,  0.08014907],
       [-1.22146904,  0.25908652],
       [ 0.97872972, -0.90400691],
       [ 1.93533788,  0.88536759],
       [-0.55184333,  0.85554468],
       [-1.69977312,  0.08014907],
       [-1.79543394,  0.13979488],
       [ 1.36137299, -0.99347563],
       [ 0.30910401,  0.46784687],
       [ 0.97872972,  0.5573156 ],
       [-1.50845149, -1.32152762],
       [ 0.30910401,  0.02050325],
       [-0.3605217 , -0.84436109],
       [ 0.50042564,  1.21341958],
       [-0.16920007,  0.82572177],
       [-0.26486088, -0.81453818],
       [ 0.40476483,  0.22926361],
       [-0.26486088,

In [40]:
# select alg
from sklearn.linear_model import LogisticRegression
sales_model=LogisticRegression(random_state=0)
sales_model.fit(X_train,Y_train)

LogisticRegression(random_state=0)

In [41]:
from sklearn.metrics import accuracy_score
y_pred=sales_model.predict(X_test)
result_score=accuracy_score(Y_test,y_pred)
result_score

0.7875

In [43]:
age=int(input("enter the age"))
salary=int(input("enter the salary"))
new_user=sc.transform([[age,salary]])
new_user

result=sales_model.predict(new_user)
if result==1:
    print("customer will purchase")
else:
    print("customer will not purchase")

enter the age32
enter the salary117000
customer will not purchase
